[package]
name = "mojibake-fix"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
encoding_rs = { version = "0.8.35", features = ["fast-kanji-encode", "fast-gb-hanzi-encode"] }
